import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '../components/navbar';
import HeroSection from '../components/heroSection';
import AboutSection from '../components/aboutSection';
import MediaSection from '../components/mediaSection';
import ContactSection from '../components/contactSection';
import Footer from '../components/footer';

const inter = Inter({ subsets: ['latin'] });

function Home() {
  return (
    <>
      <Head>
        <title>Esmeralda Tällö - Föreläsare & Inspiratör</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../assets/favicon_esmeraldatallo.ico" />
      </Head>
      <main>
        <Navbar />
        <HeroSection />
        <AboutSection />
         <MediaSection />
        <ContactSection />
        <Footer />
      </main>
    </>
  );
}

export default Home;
